name: Typescript / Setup

description: |
  Setup a Typescript project for building and testing.

branding:
  icon: settings
  color: blue

inputs:
  working-directory:
    description: Working directory
    required: false
    default: ./
  npm-token:
    description: NPM token
    required: false
    default: ''

runs:
  using: composite
  
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6
      with:
        node-version-file: ${{ inputs.working-directory }}/.tool-versions
        cache-dependency-path: ${{ inputs.working-directory }}/yarn.lock
        registry-url: 'https://registry.npmjs.org'
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
        NPM_CONFIG_ALWAYS_AUTH: ${{ inputs.npm-token != '' }}

    - name: Copy NPM Auth config
      shell: bash
      if: ${{ inputs.npm-token != '' }}
      run: |
        echo "copying .npmrc file to home directory"
        echo "  - NPM_CONFIG_USERCONFIG=$NPM_CONFIG_USERCONFIG"
        echo "  - HOME=$HOME"
        cp $NPM_CONFIG_USERCONFIG $HOME/.npmrc
        cat $HOME/.npmrc

    - name: Setup Package Manager
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        corepack enable
        yarn --version

    - name: Cache Turbo Build
      uses: actions/cache@2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2
      with:
        path: ${{ inputs.working-directory }}/.turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}-${{ github.workflow }}-${{ github.job || 'build' }}
        restore-keys: |
          ${{ runner.os }}-turbo-${{ github.sha }}-${{ github.workflow }}-${{ github.job || 'build' }}
          ${{ runner.os }}-turbo-${{ github.sha }}-${{ github.workflow }}-
          ${{ runner.os }}-turbo-${{ github.sha }}-
          ${{ runner.os }}-turbo-

    - name: Install Dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: yarn install

    - name: Turbo Run Summary
      uses: gacts/run-and-post-run@4683764dd706df847f57b9bed39d08164bcd2690
      with:
        post: |
          echo "::group::Turbo Run Summary"
          cat ${{ inputs.working-directory }}/.turbo/runs/*.json || echo 'No Turbo Run Summary found'
          echo "::endgroup::"
